// Local config plugin — fixes "Application failed to launch: UIScene life cycle is
// required for apps built with this SDK" when building against Xcode 27 / iOS 27.
//
// The `expo` package already ships the fix (node_modules/expo/ios/AppDelegates/
// ExpoAppSceneDelegate.swift, @objc name EXExpoAppSceneDelegate), but expo prebuild's
// AppDelegate.swift template doesn't wire it up yet, so this plugin does it by hand:
//   1. Info.plist: declare UIApplicationSceneManifest pointing at EXExpoAppSceneDelegate.
//   2. AppDelegate.swift: conform to ExpoReactNativeFactoryProvider (the scene delegate
//      requires it to reach the React Native factory), and remove the window creation +
//      startReactNative call from didFinishLaunchingWithOptions — the scene delegate does
//      that now when its scene connects. Leaving both in place would start React Native twice.
//
// ios/ is regenerated by `expo prebuild` (gitignored — see /ios in .gitignore), so this
// lives here rather than as a one-off hand-edit of the generated AppDelegate.swift.
// Each regex throws loudly if its target text isn't found, rather than silently no-op'ing
// against a changed template in a future Expo SDK bump.
const { withAppDelegate, withInfoPlist } = require('expo/config-plugins');

const SCENE_DELEGATE_CLASS_NAME = 'EXExpoAppSceneDelegate';

const CLASS_DECLARATION_RE = /class AppDelegate: ExpoAppDelegate(?!,)\s*\{/;

const WINDOW_START_BLOCK_RE =
  /#if os\(iOS\) \|\| os\(tvOS\)\s*\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\s*\n\s*factory\.startReactNative\(\s*\n\s*withModuleName: "main",\s*\n\s*in: window,\s*\n\s*launchOptions: launchOptions\)\s*\n#endif\s*\n/;

function withUiSceneLifecycle(config) {
  config = withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: SCENE_DELEGATE_CLASS_NAME,
          },
        ],
      },
    };
    return config;
  });

  config = withAppDelegate(config, (config) => {
    let { contents } = config.modResults;

    if (!CLASS_DECLARATION_RE.test(contents)) {
      throw new Error(
        'withUiSceneLifecycle: AppDelegate.swift class declaration not found or already ' +
          'patched. The prebuild template changed — if Expo now wires up the scene delegate ' +
          'itself, drop "./plugins/withUiSceneLifecycle" from app.json; otherwise update the ' +
          'regexes in plugins/withUiSceneLifecycle.js.'
      );
    }
    contents = contents.replace(
      CLASS_DECLARATION_RE,
      'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {'
    );

    if (!WINDOW_START_BLOCK_RE.test(contents)) {
      throw new Error(
        'withUiSceneLifecycle: window/startReactNative block not found in AppDelegate.swift. ' +
          'The prebuild template changed — if Expo now wires up the scene delegate itself, ' +
          'drop "./plugins/withUiSceneLifecycle" from app.json; otherwise update the regexes ' +
          'in plugins/withUiSceneLifecycle.js.'
      );
    }
    contents = contents.replace(WINDOW_START_BLOCK_RE, '');

    config.modResults.contents = contents;
    return config;
  });

  return config;
}

module.exports = withUiSceneLifecycle;
