-- GENERATED by scripts/build-category-sql.mjs from src/lib/category-catalog.ts.
-- Edit the catalog and re-run the script; do not edit this file by hand.
--
-- Brings the system categories in line with the catalog: mortgage options for
-- every way people pay (with escrow, without, split, escrow or PMI on its own),
-- property tax as one bill or as separate school / county / city-town bills,
-- trims categories almost nobody used, and adds a one-line description where a
-- name alone could be misread. Renames keep their rows, so entries stay put;
-- merged rows move their entries (and recurring rules) to the survivor first.
-- Idempotent: safe to run twice. User-created categories are never touched.

begin;

alter table categories add column if not exists description text;

-- 1. Renames (same row, new name).
update categories set name = 'City/Town Tax' where is_system and name = 'City/Township Tax' and kind = 'expense'
  and not exists (select 1 from categories t where t.is_system and t.name = 'City/Town Tax' and t.kind = 'expense');
update categories set name = 'Home Insurance' where is_system and name = 'Insurance' and kind = 'expense'
  and not exists (select 1 from categories t where t.is_system and t.name = 'Home Insurance' and t.kind = 'expense');
update categories set name = 'Water & Sewer' where is_system and name = 'Water' and kind = 'expense'
  and not exists (select 1 from categories t where t.is_system and t.name = 'Water & Sewer' and t.kind = 'expense');
update categories set name = 'Trash/Recycling' where is_system and name = 'Garbage' and kind = 'expense'
  and not exists (select 1 from categories t where t.is_system and t.name = 'Trash/Recycling' and t.kind = 'expense');
update categories set name = 'Renovation/Improvements' where is_system and name = 'Capital Improvement' and kind = 'expense'
  and not exists (select 1 from categories t where t.is_system and t.name = 'Renovation/Improvements' and t.kind = 'expense');
update categories set name = 'Other Rental Income' where is_system and name = 'Laundry/Vending' and kind = 'income'
  and not exists (select 1 from categories t where t.is_system and t.name = 'Other Rental Income' and t.kind = 'income');

-- 2. Merges (move entries and rules, then drop the old row). Make sure each
--    target exists first; usually it already does, or a rename above made it.
insert into categories (name, kind, scope, is_system)
select v.name, v.kind, v.scope, true
  from (values
    ('Water & Sewer', 'expense', 'both'),
    ('Other Expense', 'expense', 'both'),
    ('Other Rental Income', 'income', 'property')
  ) as v(name, kind, scope)
 where not exists (select 1 from categories c where c.is_system and c.name = v.name and c.kind = v.kind);

-- Sewer → Water & Sewer
update expenses set category_id = (select id from categories where is_system and name = 'Water & Sewer' and kind = 'expense') where category_id = (select id from categories where is_system and name = 'Sewer' and kind = 'expense');
update income set category_id = (select id from categories where is_system and name = 'Water & Sewer' and kind = 'expense') where category_id = (select id from categories where is_system and name = 'Sewer' and kind = 'expense');
update recurring_rules set category_id = (select id from categories where is_system and name = 'Water & Sewer' and kind = 'expense') where category_id = (select id from categories where is_system and name = 'Sewer' and kind = 'expense');
delete from categories where is_system and name = 'Sewer' and kind = 'expense';

-- Parking → Other Rental Income
update expenses set category_id = (select id from categories where is_system and name = 'Other Rental Income' and kind = 'income') where category_id = (select id from categories where is_system and name = 'Parking' and kind = 'income');
update income set category_id = (select id from categories where is_system and name = 'Other Rental Income' and kind = 'income') where category_id = (select id from categories where is_system and name = 'Parking' and kind = 'income');
update recurring_rules set category_id = (select id from categories where is_system and name = 'Other Rental Income' and kind = 'income') where category_id = (select id from categories where is_system and name = 'Parking' and kind = 'income');
delete from categories where is_system and name = 'Parking' and kind = 'income';

-- Savings Transfer → Other Expense
update expenses set category_id = (select id from categories where is_system and name = 'Other Expense' and kind = 'expense') where category_id = (select id from categories where is_system and name = 'Savings Transfer' and kind = 'expense');
update income set category_id = (select id from categories where is_system and name = 'Other Expense' and kind = 'expense') where category_id = (select id from categories where is_system and name = 'Savings Transfer' and kind = 'expense');
update recurring_rules set category_id = (select id from categories where is_system and name = 'Other Expense' and kind = 'expense') where category_id = (select id from categories where is_system and name = 'Savings Transfer' and kind = 'expense');
delete from categories where is_system and name = 'Savings Transfer' and kind = 'expense';

-- 3. Every catalog row: update in place, or insert when new.
create temporary table catalog (name text, kind text, scope text, tenant_only boolean, description text) on commit drop;
insert into catalog values
  ('Mortgage Payment (with Escrow)', 'expense', 'property', false, 'Your full monthly payment, including the property tax and insurance your lender pays from escrow. Do not also log those taxes or insurance.'),
  ('Mortgage Payment (no Escrow)', 'expense', 'property', false, 'Principal and interest paid to the lender. Log property taxes and insurance under their own categories when you pay them.'),
  ('Mortgage Interest', 'expense', 'property', false, 'Only the interest part of a payment you split. On a rental it is usually deductible. Use with Mortgage Principal, not with a Mortgage Payment.'),
  ('Mortgage Principal', 'expense', 'property', false, 'Only the principal part of a payment you split. It builds equity and is not deductible. Use with Mortgage Interest, not with a Mortgage Payment.'),
  ('Mortgage Escrow (Paid Separately)', 'expense', 'property', false, 'Escrow paid on its own, such as a shortage or top-up after the annual escrow review.'),
  ('Mortgage Insurance (PMI)', 'expense', 'property', false, 'Private mortgage insurance billed separately from your mortgage payment.'),
  ('HELOC / Second Mortgage', 'expense', 'property', false, 'Payments on a home equity line or a second loan against the property.'),
  ('Property Tax (Combined)', 'expense', 'property', false, 'One property tax bill covering everything. If school, county and city or town tax come separately, use those instead. Skip it if escrow pays it.'),
  ('School Tax', 'expense', 'property', false, 'School district tax billed on its own. Skip it if escrow pays it.'),
  ('County Tax', 'expense', 'property', false, 'County tax billed on its own. Skip it if escrow pays it.'),
  ('City/Town Tax', 'expense', 'property', false, 'City, town, township or village tax billed on its own. Skip it if escrow pays it.'),
  ('Home Insurance', 'expense', 'both', false, 'Homeowners, landlord or renters policy you pay directly. Skip it if escrow pays it.'),
  ('Flood Insurance', 'expense', 'property', false, 'A separate flood policy. Skip it if escrow pays it.'),
  ('Electric', 'expense', 'both', false, null),
  ('Gas/Heating', 'expense', 'both', false, 'Natural gas, propane or heating oil.'),
  ('Water & Sewer', 'expense', 'both', false, null),
  ('Trash/Recycling', 'expense', 'both', false, null),
  ('Internet/Cable', 'expense', 'both', false, null),
  ('HOA Fees', 'expense', 'both', false, 'Homeowners or condo association dues and special assessments.'),
  ('Repairs', 'expense', 'both', false, 'Fixing something that broke.'),
  ('Maintenance', 'expense', 'both', false, 'Routine upkeep: servicing, inspections, filters.'),
  ('Cleaning', 'expense', 'both', false, null),
  ('Supplies', 'expense', 'both', false, null),
  ('Appliances', 'expense', 'both', false, null),
  ('Home Warranty', 'expense', 'both', false, null),
  ('Landscaping/Snow', 'expense', 'property', false, null),
  ('Pest Control', 'expense', 'property', false, null),
  ('Renovation/Improvements', 'expense', 'property', false, 'Work that adds value or extends the life of the property: a new roof, kitchen, addition.'),
  ('Property Management Fee', 'expense', 'property', true, null),
  ('Advertising/Listing', 'expense', 'property', false, 'Finding a tenant or listing the property for sale.'),
  ('Permits/Licenses', 'expense', 'property', false, null),
  ('Travel/Mileage', 'expense', 'property', false, 'Trips to the property for upkeep or showings.'),
  ('Closing Costs', 'expense', 'property', false, 'Title, attorney, recording and lender fees when you buy or refinance.'),
  ('Selling Costs', 'expense', 'property', false, 'Agent commission, transfer tax, staging and seller closing costs.'),
  ('Legal/Professional Fees', 'expense', 'both', false, 'Attorney, accountant or tax preparer.'),
  ('Bank/Loan Fees', 'expense', 'both', false, null),
  ('Other Expense', 'expense', 'both', false, null),
  ('Groceries', 'expense', 'budget', false, null),
  ('Dining Out', 'expense', 'budget', false, null),
  ('Rent/Mortgage', 'expense', 'budget', false, 'Your housing payment. Tracking the home as a property? Log the mortgage on that property instead.'),
  ('Car Payment', 'expense', 'budget', false, null),
  ('Car Insurance', 'expense', 'budget', false, null),
  ('Fuel', 'expense', 'budget', false, null),
  ('Public Transit', 'expense', 'budget', false, null),
  ('Phone', 'expense', 'budget', false, null),
  ('Health/Medical', 'expense', 'budget', false, 'Doctor visits, prescriptions and premiums you pay yourself.'),
  ('Childcare', 'expense', 'budget', false, null),
  ('Education', 'expense', 'budget', false, null),
  ('Subscriptions', 'expense', 'budget', false, null),
  ('Clothing', 'expense', 'budget', false, null),
  ('Personal Care', 'expense', 'budget', false, null),
  ('Pets', 'expense', 'budget', false, null),
  ('Entertainment', 'expense', 'budget', false, null),
  ('Gifts', 'expense', 'budget', false, null),
  ('Travel', 'expense', 'budget', false, null),
  ('Charity', 'expense', 'budget', false, null),
  ('Debt Payment', 'expense', 'budget', false, 'Credit cards, student loans and other personal loans.'),
  ('Rent', 'income', 'property', true, null),
  ('Late Fee', 'income', 'property', true, null),
  ('Pet Fee', 'income', 'property', true, null),
  ('Security Deposit Retained', 'income', 'property', true, 'Only the part of a deposit you keep for damage or unpaid rent. A deposit you will return is not income.'),
  ('Other Rental Income', 'income', 'property', true, 'Parking, laundry, storage or utility reimbursements from tenants.'),
  ('Insurance Payout', 'income', 'property', false, 'A claim paid out for damage to the property.'),
  ('Sale Proceeds', 'income', 'property', false, 'What you received when the property sold, after the loan payoff.'),
  ('Salary', 'income', 'budget', false, null),
  ('Bonus', 'income', 'budget', false, null),
  ('Freelance', 'income', 'budget', false, null),
  ('Interest/Dividends', 'income', 'budget', false, null),
  ('Refund', 'income', 'budget', false, null),
  ('Gift Received', 'income', 'budget', false, null),
  ('Other Income', 'income', 'both', false, null);

update categories c
   set scope = k.scope, tenant_only = k.tenant_only, description = k.description
  from catalog k
 where c.is_system and c.name = k.name and c.kind = k.kind;

insert into categories (name, kind, scope, tenant_only, description, is_system)
select k.name, k.kind, k.scope, k.tenant_only, k.description, true
  from catalog k
 where not exists (select 1 from categories c where c.is_system and c.name = k.name and c.kind = k.kind);

-- 4. Nothing outside the catalog may survive as a system category.
do $$
declare stray text;
begin
  select string_agg(c.name, ', ') into stray
    from categories c
   where c.is_system and not exists (select 1 from catalog k where k.name = c.name and k.kind = c.kind);
  if stray is not null then
    raise exception 'system categories missing from the catalog: %', stray;
  end if;
end $$;

commit;
